In [14]:
import numpy as np
a=np.arange(10)
b=np.array([1,2,4,1])
print("a: ",a)
print("b: ",b)

a:  [0 1 2 3 4 5 6 7 8 9]
b:  [1 2 4 1]


In [44]:
a=np.zeros((3,4))
b=np.ones(10)
print("a: ",a)
print("b: ",b)

a:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
b:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [45]:
a=np.arange(15)
print(a)
print("Dtype: ",a.dtype)
print("Shape: ",a.shape)
a=a.reshape(3,5)
print(a)
print("Shape: ",a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Dtype:  int64
Shape:  (15,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Shape:  (3, 5)


In [62]:
a=np.arange(15).reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [63]:
np.transpose(a)

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [48]:
a=np.arange(20)
print(a)
print("a[3]= ",a[3])
print("a[4:8:-1]= ",a[4:8:-1])
a[2:10]=1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
a[3]=  3
a[4:8:-1]=  []
[ 0  1  1  1  1  1  1  1  1  1 10 11 12 13 14 15 16 17 18 19]


In [50]:
a[[3,10]]

array([ 1, 10])

In [47]:
print(np.hsplit(a,(4,16)))
a=a.reshape(4,5)
print(np.vsplit(a,2))

[array([[ 0,  1,  1,  1],
       [ 1,  1,  1,  1],
       [10, 11, 12, 13],
       [15, 16, 17, 18]]), array([[ 1],
       [ 1],
       [14],
       [19]]), array([], shape=(4, 0), dtype=int64)]
[array([[0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]]), array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])]


In [67]:
a*3

array([[  0,  27,  54],
       [ 81, 108, 135],
       [162, 189, 216],
       [243, 270, 297],
       [324, 351, 378]])

In [70]:
a=np.arange(10)
b=np.array([1,5,3,7,4,325,2,4,-2,4])
a*b

array([   0,    5,    6,   21,   16, 1625,   12,   28,  -16,   36])

In [71]:
a+b

array([  1,   6,   5,  10,   8, 330,   8,  11,   6,  13])

In [72]:
a/b

array([ 0.        ,  0.2       ,  0.66666667,  0.42857143,  1.        ,
        0.01538462,  3.        ,  1.75      , -4.        ,  2.25      ])

In [76]:
b.min()

np.int64(-2)

In [77]:
a.max()

np.int64(9)

In [91]:
a=(a-a.min())/(a.max()-a.min())
a

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [88]:
np.round(a,3)

array([0.   , 0.111, 0.222, 0.333, 0.444, 0.556, 0.667, 0.778, 0.889,
       1.   ])

In [89]:
a.mean()

np.float64(0.5)